//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumpsterDiving.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DumpsterDiving.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found an ~g~Assault Rifle~s~!.
        /// </summary>
        public static string FoundAssaultRifle {
            get {
                return ResourceManager.GetString("FoundAssaultRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~r~Boot~s~!.
        /// </summary>
        public static string FoundBoot {
            get {
                return ResourceManager.GetString("FoundBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found some ~g~BZ Gas~s~!.
        /// </summary>
        public static string FoundBZGas {
            get {
                return ResourceManager.GetString("FoundBZGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~r~Used Condom~s~!.
        /// </summary>
        public static string FoundCondom {
            get {
                return ResourceManager.GetString("FoundCondom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~r~Dildo~s~!.
        /// </summary>
        public static string FoundDildo {
            get {
                return ResourceManager.GetString("FoundDildo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~r~Fish~s~!.
        /// </summary>
        public static string FoundFish {
            get {
                return ResourceManager.GetString("FoundFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found some ~g~Frag Grenades~s~!.
        /// </summary>
        public static string FoundGrenades {
            get {
                return ResourceManager.GetString("FoundGrenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~g~Hamburger~s~!.
        /// </summary>
        public static string FoundHamburger {
            get {
                return ResourceManager.GetString("FoundHamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~g~Hot Dog~s~!.
        /// </summary>
        public static string FoundHotDog {
            get {
                return ResourceManager.GetString("FoundHotDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~g~Micro SMG~s~!.
        /// </summary>
        public static string FoundMicroSMG {
            get {
                return ResourceManager.GetString("FoundMicroSMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~r~Moldy Hamburger~s~!.
        /// </summary>
        public static string FoundMoldyHamburger {
            get {
                return ResourceManager.GetString("FoundMoldyHamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~r~Moldy Hot Dog~s~!.
        /// </summary>
        public static string FoundMoldyHotDog {
            get {
                return ResourceManager.GetString("FoundMoldyHotDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found ~g~${0}~s~!.
        /// </summary>
        public static string FoundMoney {
            get {
                return ResourceManager.GetString("FoundMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~g~Pistol~s~!.
        /// </summary>
        public static string FoundPistol {
            get {
                return ResourceManager.GetString("FoundPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~g~Sawn Off Shotgun~s~!.
        /// </summary>
        public static string FoundSawnOffShotgun {
            get {
                return ResourceManager.GetString("FoundSawnOffShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found a ~g~Shotgun~s~!.
        /// </summary>
        public static string FoundShotgun {
            get {
                return ResourceManager.GetString("FoundShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found some ~g~Tear Gas~s~!.
        /// </summary>
        public static string FoundTearGas {
            get {
                return ResourceManager.GetString("FoundTearGas", resourceCulture);
            }
        }
    }
}
