//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumpsterDiving.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DumpsterDiving.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a boot.
        /// </summary>
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a used condom.
        /// </summary>
        internal static string Condom {
            get {
                return ResourceManager.GetString("Condom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a dildo.
        /// </summary>
        internal static string Dildo {
            get {
                return ResourceManager.GetString("Dildo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumpster.
        /// </summary>
        internal static string Dumpster {
            get {
                return ResourceManager.GetString("Dumpster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a fish.
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have found {0}!.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an Assault Rifle.
        /// </summary>
        internal static string GunAssaultRifle {
            get {
                return ResourceManager.GetString("GunAssaultRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some BZ gas.
        /// </summary>
        internal static string GunBZ {
            get {
                return ResourceManager.GetString("GunBZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some Grenades.
        /// </summary>
        internal static string GunGrenades {
            get {
                return ResourceManager.GetString("GunGrenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Micro SMG.
        /// </summary>
        internal static string GunMicro {
            get {
                return ResourceManager.GetString("GunMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Pistol.
        /// </summary>
        internal static string GunPistol {
            get {
                return ResourceManager.GetString("GunPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Sawn-off Shotgun.
        /// </summary>
        internal static string GunSawnOff {
            get {
                return ResourceManager.GetString("GunSawnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Shotgun.
        /// </summary>
        internal static string GunShotgun {
            get {
                return ResourceManager.GetString("GunShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Hamburger.
        /// </summary>
        internal static string Hamburger {
            get {
                return ResourceManager.GetString("Hamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Hotdog.
        /// </summary>
        internal static string Hotdog {
            get {
                return ResourceManager.GetString("Hotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DumpsterDiving has been loaded!.
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Moldy Hamburger.
        /// </summary>
        internal static string MoldyHamburger {
            get {
                return ResourceManager.GetString("MoldyHamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Moldy Hotdog.
        /// </summary>
        internal static string MoldyHotdog {
            get {
                return ResourceManager.GetString("MoldyHotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dollars.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to search the dumpster.
        /// </summary>
        internal static string PressNotification {
            get {
                return ResourceManager.GetString("PressNotification", resourceCulture);
            }
        }
    }
}
