name: Compile Mod
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  # releases
  contents: write

jobs:
  lint-and-compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: "8.x"
      - run: dotnet restore ${{ github.event.repository.name }}.sln
      - uses: justalemon/VersionPatcher@v0.8
        with:
          version: 1.1.0.${{ github.run_number }}
          use-tag: true
          csproj-files: "**/**.csproj"
      - working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: dotnet build ${{ github.event.repository.name }}.sln -c ${{ matrix.configuration }}
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: bin/${{ matrix.configuration }}
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: "8.0.x"
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}/bin/Release/*
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ github.event.repository.name }}.zip
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
